### ISSUE TITLE
List of new snippets

### ISSUE THREAD

**Issue by username-is-already-taken2** [chef-training/extension-inspec#8]
I've attempted to reconcile a list of new resources in inspec of which we need to create snippets for.
I will attempt to work on these hopefully getting them completed before ChefConf

- [ ]  crontab
- [ ] docker
- [ ] docker_container
- [ ] docker_image
- [ ] http
- [ ] kernel_parameter
- [ ] key_rsa
- [ ] login_def (propose to rename login_defs.json to login_def.json to match inspec)
- [ ] oracledb_session
- [ ] rabbitmq_config
- [ ] x509_certificate
- [ ] zfs_dataset
- [ ] zfs_pool

**Comment by kmf** [comment]
awesome!

**Comment by burtlo** [comment]
Thanks these snippets should now be in InSpec 0.4.3.
